// Writes src/components/logos.ts from assets/: each logo's viewBox and inner
// markup, for HomeLink to inline. Run it (`npm run logos`) after changing an
// SVG in assets/; `npm run build` runs it first, and a test fails if the two
// disagree.
import { readFileSync, writeFileSync } from "node:fs";

const LOGOS = { logoFull: "logo-full.svg", logoIcon: "icon-only-logo.svg" };

const root = new URL("..", import.meta.url);
const parse = (file) => {
  const svg = readFileSync(new URL(`assets/${file}`, root), "utf8").trim();
  const m = /^<svg\b[^>]*\bviewBox="([^"]+)"[^>]*>([\s\S]*)<\/svg>$/.exec(svg);
  if (!m) throw new Error(`assets/${file}: expected one <svg> with a viewBox`);
  if (/['\\\n]/.test(m[2]))
    throw new Error(`assets/${file}: unexpected quote, backslash or newline`);
  return { viewBox: m[1], markup: m[2] };
};

let out =
  "// Generated by scripts/logos.mjs from assets/. Don't edit: change the SVG and run\n" +
  "// `npm run logos`.\n";
for (const [name, file] of Object.entries(LOGOS)) {
  const { viewBox, markup } = parse(file);
  out += `\n/** assets/${file} */\nexport const ${name} = {\n  viewBox: ${JSON.stringify(viewBox)},\n  markup:\n    '${markup}',\n};\n`;
}
writeFileSync(new URL("src/components/logos.ts", root), out);
